### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jayanpraveen** [realaravinth/ids-matrix#1]
## Typo in README.md

WARNING: realaravinth/ids-matrix comes with ABSOLUTELY NO **_WARRANY_**, to the extent permitted by applicable law. 
keyword: **_WARRANY_**

**Comment by realaravinth** [comment]
Thanks for pointing out but please refrain from raising such issues. Spelling mistakes, though embarrassing, are not worth raising issues. 

Edit: I mistook this for a PR.

**Comment by jayanpraveen** [comment]
I'm sorry, I'm new here.
